# Generated by Django 4.0.3 on 2022-03-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
